name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Choose your preferred distribution (e.g., zulu, adopt)
          java-version: '17'      # Use your project's required Java version

      # Step 3: Build the project
      - name: Build with Gradle/Maven
        run: |
          # For Gradle
          ./gradlew build

          # If using Maven, uncomment the below line and comment out Gradle
          # mvn clean compile

      # Step 4: Run Unit Tests
      - name: Run Tests
        run: |
          # For Gradle
          ./gradlew test

           mvn test
